server:
  port: 8080
spring:
  psql:
    console:
      enabled: true
      path: /postgresql
  datasource:
    url: ${PSQL_DB_URL}
    username: ${PSQL_DB_USR}
    password: ${PSQL_DB_PWD}
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate.ddl-auto: create-drop